FROM python:3.10.10

WORKDIR /app/server

# install packages
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn==23.0.0 gevent==24.2.1 gevent-websocket==0.10.1

COPY . .

CMD ["gunicorn", "-k", "geventwebsocket.gunicorn.workers.GeventWebSocketWorker", "-w", "1", "--threads", "100", "-b", "0.0.0.0:8080", "app:app"]